bootstrap: "172.18.0.1:9292,172.18.1.1:9092,172.18.2.1:9092,172.18.3.1:9092"
producer: 1
consumer: 1
ack: all
topic:
  name: kafka-benchmark
  partitions: 4
  replicationFactor: 2
payload:
  total: 209715200 # 1Gi
  msgSize: 1024 # 4Ki
# entity: single, end2end
entity: end2end
