# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: predict.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='predict.proto',
  package='com.aagmon.demos',
  syntax='proto3',
  serialized_options=_b('Z\031aagmon/kafkaClientP/proto'),
  serialized_pb=_b('\n\rpredict.proto\x12\x10\x63om.aagmon.demos\":\n\x0ePredictRequest\x12\x10\n\x08recordID\x18\x01 \x01(\t\x12\x16\n\x0e\x66\x65\x61turesVector\x18\x04 \x03(\x02\x42\x1bZ\x19\x61\x61gmon/kafkaClientP/protob\x06proto3')
)




_PREDICTREQUEST = _descriptor.Descriptor(
  name='PredictRequest',
  full_name='com.aagmon.demos.PredictRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='recordID', full_name='com.aagmon.demos.PredictRequest.recordID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='featuresVector', full_name='com.aagmon.demos.PredictRequest.featuresVector', index=1,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['PredictRequest'] = _PREDICTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PredictRequest = _reflection.GeneratedProtocolMessageType('PredictRequest', (_message.Message,), dict(
  DESCRIPTOR = _PREDICTREQUEST,
  __module__ = 'predict_pb2'
  # @@protoc_insertion_point(class_scope:com.aagmon.demos.PredictRequest)
  ))
_sym_db.RegisterMessage(PredictRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
