include_guard(GLOBAL)
option(EMBARCADERO_ENABLE_FAULT_INJECTION "Enable test-only production fault controls" OFF)
option(EMBARCADERO_NATIVE_ARCH "Optimize project targets for the build host ISA" OFF)
set(EMBARCADERO_SANITIZER "none" CACHE STRING "Instrumentation: none, address-undefined, or thread")
set_property(CACHE EMBARCADERO_SANITIZER PROPERTY STRINGS none address-undefined thread)
if(NOT EMBARCADERO_SANITIZER MATCHES "^(none|address-undefined|thread)$")
    message(FATAL_ERROR "Unknown EMBARCADERO_SANITIZER: ${EMBARCADERO_SANITIZER}")
endif()
add_library(embarcadero_build_options INTERFACE)
target_compile_options(embarcadero_build_options INTERFACE -Wall)
if(EMBARCADERO_NATIVE_ARCH)
    include(CheckCXXCompilerFlag)
    check_cxx_compiler_flag("-march=native" EMBARCADERO_COMPILER_HAS_NATIVE)
    if(NOT EMBARCADERO_COMPILER_HAS_NATIVE)
        message(FATAL_ERROR "Compiler does not support requested -march=native")
    endif()
    target_compile_options(embarcadero_build_options INTERFACE -march=native)
endif()
# Existing x86 publication primitives require CLFLUSHOPT even without native tuning.
if(CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|AMD64|amd64")
    include(CheckCXXCompilerFlag)
    check_cxx_compiler_flag("-mclflushopt" EMBARCADERO_COMPILER_HAS_CLFLUSHOPT)
    if(NOT EMBARCADERO_COMPILER_HAS_CLFLUSHOPT)
        message(FATAL_ERROR "The x86 publication primitives require -mclflushopt")
    endif()
    target_compile_options(embarcadero_build_options INTERFACE -mclflushopt)
endif()
if(NOT EMBARCADERO_SANITIZER STREQUAL "none")
    if(NOT CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
        message(FATAL_ERROR "Sanitizer presets require GCC or Clang")
    endif()
    if(EMBARCADERO_SANITIZER STREQUAL "address-undefined")
        set(_embarcadero_sanitize "-fsanitize=address,undefined")
    else()
        set(_embarcadero_sanitize "-fsanitize=thread")
    endif()
    # Abseil changes container layout under sanitizer feature macros. Instrument
    # fetched C/C++ dependencies as well as project targets, before FetchContent
    # creates them, so header instantiations and linked archives share an ABI.
    add_compile_options("$<$<COMPILE_LANGUAGE:C,CXX>:${_embarcadero_sanitize}>"
                        "$<$<COMPILE_LANGUAGE:C,CXX>:-fno-omit-frame-pointer>")
    add_link_options("${_embarcadero_sanitize}")
    # Legacy symbol interposition runs during loader initialization and conflicts
    # with sanitizer interceptors. Instrumented builds require the native runtime.
    set(EMBARCADERO_LEGACY_COMPAT_SOURCE "")
else()
    set(EMBARCADERO_LEGACY_COMPAT_SOURCE "${PROJECT_SOURCE_DIR}/src/common/compat_isoc23.cpp")
endif()
function(embarcadero_apply_options directory)
    get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
    foreach(target IN LISTS targets)
        get_target_property(kind "${target}" TYPE)
        if(kind MATCHES "^(EXECUTABLE|STATIC_LIBRARY|SHARED_LIBRARY|MODULE_LIBRARY|OBJECT_LIBRARY)$")
            set_property(TARGET "${target}" APPEND PROPERTY LINK_LIBRARIES embarcadero_build_options)
        endif()
    endforeach()
    get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
    foreach(child IN LISTS children)
        embarcadero_apply_options("${child}")
    endforeach()
endfunction()
function(embarcadero_collect_tests directory output)
    get_property(names DIRECTORY "${directory}" PROPERTY TESTS)
    get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
    foreach(child IN LISTS children)
        embarcadero_collect_tests("${child}" child_names)
        list(APPEND names ${child_names})
    endforeach()
    set("${output}" "${names}" PARENT_SCOPE)
endfunction()
function(embarcadero_write_test_inventory)
    embarcadero_collect_tests("${PROJECT_SOURCE_DIR}/src" names)
    embarcadero_collect_tests("${PROJECT_SOURCE_DIR}/test" test_names)
    list(APPEND names ${test_names})
    foreach(required IN ITEMS unit_blog_header_validation unit_phase2_integration unit_chain_pipeline
            unit_session_proto_roundtrip unit_order5_session_fencing unit_order5_publisher_rollover unit_order5_subscriber_reorder)
        if(NOT required IN_LIST names)
            message(FATAL_ERROR "Required test was not registered: ${required}")
        endif()
    endforeach()
    list(SORT names)
    list(LENGTH names count)
    string(REPLACE ";" "\n" inventory "${names}")
    file(WRITE "${PROJECT_BINARY_DIR}/test-inventory.txt" "${inventory}\n")
    message(STATUS "Registered ${count} project tests; inventory: ${PROJECT_BINARY_DIR}/test-inventory.txt")
endfunction()
